---
- name: Determine if the default instance exists.
  ansible.windows.win_service:
    name: 'MSSQLSERVER'
  register: service_info

- name: End play if default instance already exists.
  when: service_info.exists
  ansible.builtin.meta: end_play

- name: Begin SQL Install Task
  when: not service_info.exists
  block:
    - name: Set Windows power plan to high performance
      community.windows.win_power_plan:
        name: high performance

    - name: Create temp folder on target
      ansible.windows.win_file:
        path: "{{ sql_install_files_path }}"
        state: directory

    - name: Copy the Configuration.ini file to target
      ansible.windows.win_template:
        src: sql_ini.j2
        dest: "{{ sql_install_files_path }}\\Configuration.ini"

    # - name: Copy ISO to target
    #   ansible.windows.win_get_url:
    #     url: "{{ sql_install_dir_http_url_path }}/{{ sql_install_iso }}"
    #     dest: "{{ sql_install_files_path }}\\{{ sql_install_iso }}"
    #     force: false

    - name: Mount ISO
      community.windows.win_disk_image:
        image_path: "{{ sql_install_files_path }}\\{{ sql_install_iso }}"
        state: present
      register: disk_image_out

    - name: Debug disk_image_out
      ansible.builtin.debug:
        var: disk_image_out.mount_paths[0]

    - name: Install Default instance
      ansible.windows.win_command:
        cmd: "{{ disk_image_out.mount_paths[0] }}setup.exe /ConfigurationFile=\"{{ sql_install_files_path }}\\Configuration.ini\" \"/SAPWD={{ SAPWD }}\""
      register: install_out

    - name: Debug install
      ansible.builtin.debug:
        var: install_out

    - name: Unmount ISO
      community.windows.win_disk_image:
        image_path: "{{ sql_install_files_path }}\\{{ sql_install_iso }}"
        state: absent

# setup.exe /q /IACCEPTSQLSERVERLICENSETERMS=YES /ProductKey=YOUR_LICENSE_KEY
# don't include line if arg doesn't exist
# https://github.com/automatesql/Ansible-for-SQL-Server-DBAs/blob/main/Simple-SQL-Server-Install/playbook_installSQLServer.yml
